public enum TokenType {
    IDENTIFIER,
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    KEYWORD,
    BOOLEAN_LITERAL,
    OPERATOR,
    RELATIONAL_OPERATOR,
    SINGLE_LINE_COMMENT,
    ERROR,
    DELIMITER
}
